version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_container
    restart: always
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - ./web-content:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=example.com
      - NGINX_PORT=80
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - webnet

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.10.0
    container_name: filebeat
    user: root 
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
    networks:
      - webnet
    depends_on:
      - nginx
    restart: always

networks:
  webnet:
    driver: bridge

volumes:
  nginx-conf:
  web-content:
