filebeat.inputs:
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

filebeat.modules:
- module: nginx
  access:
    enabled: true
  error:
    enabled: true

output.elasticsearch:
  hosts: ['elasticsearch_host:9200']

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"
